### ISSUE TITLE
 Caused by: java.lang.VerifyError: com/google/vrtoolkit/cardboard/CardboardDeviceParams

### ISSUE THREAD

**Issue by KingWu** [googlesamples/cardboard-unity#12]
Just try demo. Get it crash error. Anyone know it?

01-24 15:24:12.468    7271-7271/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 4.6.0b20
    Device model      : Xiaomi HM 1SW
    Device fingerprint: Xiaomi/armani/armani:4.3/JLS36C/JHCMIBH45.0:user/release-keys
    Caused by: java.lang.VerifyError: com/google/vrtoolkit/cardboard/CardboardDeviceParams
            at com.google.vrtoolkit.cardboard.HeadMountedDisplayManager.createCardboardDeviceParams(HeadMountedDisplayManager.java:214)
            at com.google.vrtoolkit.cardboard.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:54)
            at com.google.vrtoolkit.cardboard.CardboardView.init(CardboardView.java:768)
            at com.google.vrtoolkit.cardboard.CardboardView.<init>(CardboardView.java:263)
            at com.google.vrtoolkit.cardboard.plugins.unity.UnityCardboardActivity.onCreate(UnityCardboardActivity.java:184)
            at android.app.Activity.performCreate(Activity.java:5135)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2182)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
            at android.app.ActivityThread.access$600(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5162)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:756)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:572)
            at miui.dexspy.DexspyInstaller.main(DexspyInstaller.java:171)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by EnnouriMK** [comment]
Hello,
I had the same problem and solve it by Updating the SDK tools to revision 22.3 and the SDK Platform-Tool to revision 19.0.  in the SDK Manager.

**Comment by KingWu** [comment]
Thank @EnnouriMK 
I try to update SDK tools to revision 24.0 and the SDK Platform-Tool to revision 20.0.0. But, the issue still exist.

**Comment by EnnouriMK** [comment]
Hello,
Make sure you are pointing to this updated version of the SDK in Unity "Edit/Preferences/External Tools/Android SDK Location"

**Comment by KingWu** [comment]
Checked. Everything is latest. no mistake. But, issue still exist=[

**Comment by smdol** [comment]
Two things to check:
1)  In the Unity Player settings, make sure the Minimum API setting is not newer than your phone.
2)  Do you have another model of phone you can try it on?

**Comment by smdol** [comment]
Verify-errors relating to CardboardDeviceParams appear to be caused by a missing libprotobuf jar file.  Make sure it is present in Assets/Plugins/Android and that it is included in the build.
