### ISSUE TITLE
UnityVrActivityListener cast exception

### ISSUE THREAD

**Issue by theqwertman** [googlesamples/cardboard-unity#192]
```
I/Unity   (28405): Creating Cardboard object
I/Unity   (28405):
I/Unity   (28405): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
I/Unity   (28405):
E/Unity   (28405): Exception creating object com.google.vr.platform.unity.UnityVrActivityListener: UnityEngine.AndroidJavaException: java.lang.ClassCastExcep
tion: com.unity3d.player.UnityPlayerNativeActivity cannot be cast to com.google.unity.GoogleUnityActivity
E/Unity   (28405): java.lang.ClassCastException: com.unity3d.player.UnityPlayerNativeActivity cannot be cast to com.google.unity.GoogleUnityActivity
E/Unity   (28405):      at com.google.vr.platform.unity.UnityVrActivityListener.<init>(UnityVrActivityListener.java:114)
E/Unity   (28405):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   (28405):      at com.unity3d.player.UnityPlayer.a(Unknown Source)
E/Unity   (28405):      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
E/Unity   (28405):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
E/Unity   (28405):   at UnityEngine.AndroidJNISafe.NewObject (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0
E/Unity   (28405):   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0
E/Unity   (28405):   at UnityEngine.And
```

Seems like the stack trace is cut off. This is on a Kitkat Galaxy Note 4

**Comment by theqwertman** [comment]
This was caused by using an incorrect Android Manifest xml
