### ISSUE TITLE
java.lang.RuntimeException: glAttachShader: glError 1280

### ISSUE THREAD

**Issue by qwarnant** [googlesamples/cardboard-unity#8]
Hello,

I ran into an issue with the Cardboard SDK. The device is running on Android 4.1.2 (it's also a very old Samsung device). I don't know precisely if the origin of the problem is coming from the Cardboard SDK (the RuntimeException occurred in the Cardboard SDK) or Unity3D itself (an OpenGL ES problem ?). When in doubt, I post the stacktrace of the error.

> java.lang.NoClassDefFoundError: com/unity3d/player/UnityPlayer$2
	at com.unity3d.player.UnityPlayer.setScreenSize(Unknown Source)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.a(Unknown Source)
	at com.unity3d.player.UnityPlayer$a.run(Unknown Source)
Caused by: java.lang.RuntimeException: glAttachShader: glError 1280
	at com.google.vrtoolkit.cardboard.DistortionRenderer.checkGlError(DistortionRenderer.java:782)
	at com.google.vrtoolkit.cardboard.DistortionRenderer.createProgram(DistortionRenderer.java:682)
	at com.google.vrtoolkit.cardboard.DistortionRenderer.createProgramHolder(DistortionRenderer.java:717)
	at com.google.vrtoolkit.cardboard.DistortionRenderer.createProgramHolder(DistortionRenderer.java:699)
	at com.google.vrtoolkit.cardboard.DistortionRenderer.updateTextureAndDistortionMesh(DistortionRenderer.java:414)
	at com.google.vrtoolkit.cardboard.DistortionRenderer.undistortTexture(DistortionRenderer.java:235)
	at com.google.vrtoolkit.cardboard.CardboardView$RendererHelper$11.run(CardboardView.java:938)
	at com.google.vrtoolkit.cardboard.CardboardView.queueEvent(CardboardView.java:708)
	at com.google.vrtoolkit.cardboard.CardboardView$RendererHelper.undistortTexture(CardboardView.java:935)
	at com.google.vrtoolkit.cardboard.CardboardView.undistortTexture(CardboardView.java:630)
	at com.google.vrtoolkit.cardboard.plugins.unity.UnityCardboardActivity.renderUndistortedTextureInternal(UnityCardboardActivity.java:148)
	at com.google.vrtoolkit.cardboard.plugins.unity.UnityCardboardActivity.renderUndistortedTexture(UnityCardboardActivity.java:143)
>	... 3 more

Thank you for your help !

**Comment by Derek-Chen** [comment]
We've tried option #2:
2) Edit Cardboard.cs and add a try/catch around the call to GL.IssuePluginEvent(). No idea if this will recover nicely on the next frame.

so far, we haven't seen any crashes. :) Thanks!
we can't get logcat to capture this. it's kind of hard to reproduce.

Regards,
-Derek

**Comment by smdol** [comment]
The new release (v0.4.5) should no longer have this problem.
