### ISSUE TITLE
Unity 5.2 IL2CPP + SDK Status

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#87]
I was not expecting that would work but I htought it would useful to give it a try and post status here.
At the moment it is not working and the crash log is:

```
I/ActivityManager(  734): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.mick.we.ep0/com.google.unity.GoogleUnityActivity} from uid 2000 on display 0

V/WindowManager(  734): addAppToken: AppWindowToken{133f886b token=Token{3615b1ba ActivityRecord{189682e5 u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity t9304}}} to stack=1 task=9304 at 0
D/audio_hw_primary(  187): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=4
V/WindowManager(  734): Adding window Window{2010dfe0 u0 Starting com.mick.we.ep0} at 9 of 17 (after Window{35a4e697 u0 com.devhd.feedly/com.devhd.feedly.Main})
I/ActivityManager(  734): Start proc 28355:com.mick.we.ep0/u0a166 for activity com.mick.we.ep0/com.google.unity.GoogleUnityActivity
V/ActivityManager(  734): Display changed displayId=0
I/ActivityManager(  734): Config changes=480 {1.0 208mcc15mnc fr_FR ?layoutDir sw360dp w598dp h335dp 480dpi nrml land finger -keyb/v/h -nav/h s.68}
I/InputReader(  734): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  734): Device reconfigured: id=4, name='touch_dev', size 1080x1920, orientation 1, mode 1, display id 0
W/ResourceType(28355): Invalid package identifier when getting bag for resource number 0x00000000
V/WindowManager(  734): Adding window Window{10f7625b u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity} at 12 of 19 (before Window{2010dfe0 u0 Starting com.mick.we.ep0})
V/WindowManager(  734): Adding window Window{e142bd1 u0 SurfaceView} at 12 of 20 (before Window{10f7625b u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity})
V/WindowManager(  734): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: loop number 4, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: loop number 5, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
E/WindowManager(  734): Performed 6 layouts in a row. Skipping
V/WindowManager(  734): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: loop number 4, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: On entry to LockedInner, mPendingLayoutChanges = 0x1
V/WindowManager(  734): Layouts looping: loop number 5, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: after finishPostLayoutPolicyLw, mPendingLayoutChanges = 0x0
V/WindowManager(  734): Layouts looping: mLayoutNeeded, mPendingLayoutChanges = 0x1
E/WindowManager(  734): Performed 6 layouts in a row. Skipping
I/ActivityManager(  734): Displayed com.mick.we.ep0/com.google.unity.GoogleUnityActivity: +446ms
I/Keyboard.Facilitator(20346): onFinishInput()
I/WindowManager(  734): Screen frozen for +428ms due to Window{2010dfe0 u0 Starting com.mick.we.ep0}
I/ConfigService( 1219): onDestroy
F/libc    (28355): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x94 in tid 28387 (UnityMain)
I/libc    (28355): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
I/WindowState(  734): WIN DEATH: Window{10f7625b u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity}
W/WindowManager(  734): Force-removing child win Window{e142bd1 u0 SurfaceView} from container Window{10f7625b u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity}
I/Zygote  (  198): Process 28355 exited due to signal (11)
W/WindowManager(  734): Failed looking up window
W/WindowManager(  734): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@6aecaf8 does not exist
W/WindowManager(  734):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8539)
W/WindowManager(  734):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8530)
W/WindowManager(  734):         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
W/WindowManager(  734):         at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  734): WIN DEATH: null
I/ActivityManager(  734): Process com.mick.we.ep0 (pid 28355) has died
W/ActivityManager(  734): Force removing ActivityRecord{189682e5 u0 com.mick.we.ep0/com.google.unity.GoogleUnityActivity t9304}: app died, no saved state
```

Cheers!

**Comment by smdol** [comment]
Can you enabled the Development Build in the Build Settings dialog?  That will give more of a stack trace when the SIGSEGV happens.

**Comment by MiCkSoftware** [comment]
It's now up and running with 5.2.2; I've probably run into this bug:
(726121) - Android: IL2CPP - Fixed crash on startup when OBB is enabled.

PS: no noticeable performance improvement. Longer build time.
